import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "./components/containers/navbar";
import Footers from "./components/containers/footers";
import QueryProvider from "./provider/query-provider";

const inter = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <div className="container mx-auto">
          <NavBar />
          <QueryProvider>{children}</QueryProvider>
          </div>
          <Footers /> */}
        <QueryProvider>
          {children}
          <Footers />
        </QueryProvider>
      </body>
    </html>
  );
}
